### ISSUE TITLE
Unresolved dependency dotty_2.11:0.1-SNAPSHOT

### ISSUE THREAD

**Issue by dotta** [smarter/dotty-bridge#4]
Compiling the project results in an unresolved dependency

```
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: ch.epfl.lamp#dotty_2.11;0.1-SNAPSHOT: not found
```

I could fix this by changing the dotty version number in the build to `0.1-20160930-93d4c8c-NIGHTLY` (check https://repo1.maven.org/maven2/ch/epfl/lamp/dotty_2.11/ for the latest version), but maybe there is a better way to fix this that doesn't require providing a fixed version (I'm actually wondering why dotty isn't publishing SNAPSHOT (anymore?)).

**Comment by smarter** [comment]
We're having some infrastructure issues (/cc @felixmulder ), hopefully we'll be able to publish snapshots soon.

**Comment by smarter** [comment]
By the way, this project is obsolete, the dotty-bridge has now been integrated into dotty, instructions for compiling it are in https://github.com/smarter/dotty-example-project#requirements
